spring:
  cloud:
    consul:
      host: consul.hodgepodge.com
      port: 8500
      discovery:
        tags: version=0.0.1,author=cd871127
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}
        query-passing: true
        prefer-ip-address: true
        health-check-critical-timeout: 30s
        health-check-timeout: 10s
        deregister: true