spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: cd123321
    username: cdistc
    url: jdbc:mysql://mysql.hodgepodge.com:3306/hodgepodge?useUnicode=true&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC&allowPublicKeyRetrieval=true
#  characterEncoding=utf8mb4&
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #  type-aliases-package:

#  mapper-locations: classpath:sql-map/*.xml

pagehelper:
  reasonable: true
  params: count=countSql
  row-bounds-with-count: true
  support-methods-arguments: true
  auto-dialect: mysql