spring:
  jackson:
    default-property-inclusion: non_null
  main:
    allow-bean-definition-overriding: true

management:
  endpoint:
    refresh:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"