spring:
  cloud:
    consul:
      host: 172.28.0.3
      port: 8500
      discovery:
        tags: version=0.0.1,author=cd871127
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        instanceId: ${spring.application.name}:${random.value}
        query-passing: true
        prefer-ip-address: true
        health-check-critical-timeout: 30s
        health-check-timeout: 10s
